//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Course.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderLine = new HashSet<OrderLine>();
        }
    
        public int ProductId { get; set; }
        [Required(ErrorMessage = "請輸入商品名稱")]
        [StringLength(5, ErrorMessage = "商品名稱過長")]
        [DisplayName("商品名稱")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "請輸入價格")]
        [Range(10, 500, ErrorMessage = "價格範圍:10-500")]
        [DisplayName("價格")]
        [DisplayFormat(DataFormatString ="{0:N0}")]
        public decimal? Price { get; set; }
        [Required]
        [DisplayName("狀態")]
        public bool? Active { get; set; }
        [Required(ErrorMessage = "尚未輸入")]
        public decimal? Stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLine> OrderLine { get; set; }
    }
}
